const vm=require('vm'),fs=require('fs'),assert=require('assert'),alpha=require('@coderline/alphatab');
const elements=new Map(),listeners={},data=new Map();
function el(id){if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',style:{},pause(){},dataset:{},classList:{toggle(){},remove(){}},addEventListener(t,fn){listeners[id+':'+t]=fn},showModal(){this.open=true},close(){this.open=false}});return elements.get(id);}
const ctx=vm.createContext({document:{querySelector:el,querySelectorAll:()=>[],addEventListener:(t,fn)=>{(listeners[t]??=[]).push(fn)}},window:{history:{replaceState(){}},addEventListener(){},scrollTo(){}},location:{hash:''},localStorage:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)},indexedDB:{open:()=>({})},URL,console,setTimeout,clearTimeout,setInterval,clearInterval,Date,performance,TextEncoder,crypto:require('crypto').webcrypto,FormData:class{constructor(f){this.f=f.fields}get(k){return this.f[k]}}});
for(const f of ['resources.js','audio.js','app.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),ctx);
for(const page of ['inicio','repertorio','estudos','metronomo','acordes','ideias','audio','recursos']){vm.runInContext(`render('${page}')`,ctx);assert(el('#main').innerHTML.length>500,page);assert(!el('#main').innerHTML.includes('undefined'),page);}
vm.runInContext("render('repertorio')",ctx);listeners['#songform:submit']({preventDefault(){},target:{fields:{title:'Teste <script>',artist:'Ivan',key:'Am',bpm:'100',status:'Estudando',notes:'Am G'},reset(){}}});assert(JSON.parse(data.get('palco-songs')).length===4);assert(el('#main').innerHTML.includes('&lt;script&gt;'));el('#search').value='Teste';el('#filter').value='';vm.runInContext('filterSongs()',ctx);assert(el('#results').innerHTML.includes('Teste'));assert(!el('#results').innerHTML.includes('Horizonte'));
const midi69=vm.runInContext('AudioLab.guitar(69)',ctx);assert(midi69.string===1&&midi69.fret===5);assert(vm.runInContext('AudioLab.guitar(30)',ctx)===null);
const scoreXML=vm.runInContext('AudioLab.exportXML({name:"Música <&>",bpm:90,notes:[{midi:69,start:0,duration:.666,confidence:.9},{midi:67,start:1.333,duration:.666,confidence:.9},{midi:64,start:3,duration:.6,confidence:.9}]})',ctx);
const score=alpha.importer.ScoreLoader.loadScoreFromBytes(new TextEncoder().encode(scoreXML));assert(score.tracks.length===1);const bars=score.tracks[0].staves[0].bars;assert(bars.length>=2);const notes=bars.flatMap(b=>b.voices.flatMap(v=>v.beats.flatMap(beat=>beat.notes)));assert(notes.length>=3);assert(score.tracks[0].staves[0].stringTuning.tunings.length===6,'Six-string guitar tuning required');assert(notes.some(n=>n.fret===5&&n.string===6),'Tab fret must survive export');assert(scoreXML.includes('Música &lt;&amp;&gt;'));
console.log('PASS: 8 rotas, cadastro/persistência/busca, escape de texto, digitação da guitarra e MusicXML importado pelo alphaTab com notas e pausas.');
